.gitignore, app/View/Components/About.php, app/View/Components/Footer.php, package-lock.json, package.json, public/storage/.gitignore, resources/css/app.css, resources/views/about.blade.php, resources/views/components/about.blade.php, resources/views/components/footer.blade.php, resources/views/components/header.blade.php, resources/views/components/layout.blade.php, resources/views/components/nav-link.blade.php, resources/views/components/navbar.blade.php, resources/views/consoles.blade.php, resources/views/games.blade.php, resources/views/home.blade.php, resources/views/login/index.blade.php, resources/views/register/index.blade.php, routes/web.php, tailwind.config.js
Landing Page - About Section (revisi 1)
=> Landing Page - About Section (revisi 1)

.gitignore, app/View/Components/LayoutDashboard.php, app/View/Components/NavbarDashboard.php, app/View/Components/Sidebar.php, resources/views/components/nav-link.blade.php, resources/views/components/navbar.blade.php, resources/views/consoles.blade.php, resources/views/dashboard/components/layout-dashboard.blade.php, resources/views/dashboard/components/navbar-dashboard.blade.php, resources/views/dashboard/components/sidebar.blade.php, resources/views/dashboard/index.blade.php, resources/views/games.blade.php, resources/views/home.blade.php, resources/views/login/index.blade.php, resources/views/register/index.blade.php, routes/web.php
1. Revisi Card Produk di halaman home
2. Revisi UI Login
3. Revisi UI Register
4. Layout Dashboar Admin
=> Dev front end

resources/views/login/index.blade.php
Fix Type kolom password page login
=> [FIX] bug kolom password Login

composer.lock, resources/views/components/navbar.blade.php
=> style : Update Page : Landing Page

resources/views/consoles.blade.php, resources/views/forgot-password/index.blade.php, resources/views/forgot-password/reset-password.blade.php, resources/views/games.blade.php, resources/views/home.blade.php, resources/views/login/index.blade.php, routes/web.php
1. Halaman Forgot password
2. Reset Password
3. Halaman Produk & Halaman Console Responsive Mobile
=> Style: Update page forgot password

resources/views/components/navbar.blade.php, resources/views/login/index.blade.php, resources/views/profile.blade.php, resources/views/register/index.blade.php, resources/views/register/otp.blade.php
1. Menambahkan Background dan Logo pada Halaman Login
2. Menambahkan Background dan Logo pada Halaman Register
3. Menambahkan Background dan Logo pada Halaman Otp
=> Style: Mengupdate Login, Register & Otp 

app/Http/Controllers/Products/ProductController.php
- revisi body (not JSON)
- response string
=> [REVISI] input data product

composer.json, config/app.php, package-lock.json, package.json, resources/css/app.css, resources/js/app.js, resources/views/components/layout-dashboard.blade.php, resources/views/components/navbar.blade.php, resources/views/components/sidebar.blade.php, resources/views/dashboard/genre-game/index.blade.php, resources/views/dashboard/index.blade.php, resources/views/dashboard/product-console/create.blade.php, resources/views/dashboard/product-console/edit.blade.php, resources/views/dashboard/product-console/index.blade.php, resources/views/dashboard/product-console/show.blade.php, resources/views/dashboard/product-game/create.blade.php, resources/views/dashboard/product-game/edit.blade.php, resources/views/dashboard/product-game/index.blade.php, resources/views/dashboard/product-game/show.blade.php, resources/views/detail-console.blade.php, resources/views/detail-game.blade.php, routes/web.php
1. Menambahkan Halaman Utama Dashboar Admin
2. Menambahkan Halaman Product Game di Dashboard Admin
3. Menambahkan Halaman Create Product Game
4. Menambahkan Halaman Edit Product Game
5. Menambahkan Halaman Show Product Game
6. Menambahkan Halaman Product Console di Dashboard Admin
7. Menambahkan Halaman Create Product Console
8. Menambahkan Halaman Edit Product Console
9. Menambahkan Halaman Show Product Console
10. Menambahkan Route Dashboard Admin Untuk FrontEnd
=> [UPDATE] Dashboard Admin

resources/views/components/navbar.blade.php, resources/views/payment/form-payment.blade.php, resources/views/profile-users/change-password.blade.php, resources/views/profile-users/history-order.blade.php, resources/views/profile-users/profile.blade.php, routes/web.php
1. Menambahkan Form Alamat pada Dashboard User
2. Menambahkan Form Nomor Handphone pada Dahsboard User
3. Menambahkan Halaman Riwayat Pesanan pada Dashboard User
4. Menambahkan Routes Dashboard User
=>  [UPDATE] Dashboard User

resources/views/components/navbar.blade.php, resources/views/detail-ewallet.blade.php, resources/views/detail-game.blade.php, resources/views/ewallet.blade.php, resources/views/forgot-password/index.blade.php, resources/views/forgot-password/reset-password.blade.php, resources/views/register/otp.blade.php, routes/web.php
1. Menambahkan Halaman E-wallet
2. Menambahkan Halaman detail E-wallet
3. Menambahkan Routes Halaman E-wallet
4. Menambahkan Routes Halaman detail E-wallet
=> Style : Adding E-wallet Page & Added e-wallet and e-wallet details page

app/Http/Controllers/HomeController.php, resources/views/home.blade.php, routes/web.php
1. Menampilkan Data Produk pada halaman home
=> Style: Update Menampilkan data produk pada halaman home

app/Http/Controllers/Auth/AuthentikasiController.php, app/Http/Middleware/CheckUser.php, app/Http/Middleware/RoleAccess.php, app/Providers/AppServiceProvider.php, app/Services/AuthService.php, resources/views/components/navbar.blade.php, resources/views/dashboard/products/index.blade.php, resources/views/dashboard/products/show-product.blade.php, resources/views/unauthorized/index.blade.php, routes/web.php
- Implemented RBAC to restrict access to admin-only pages.
- Added caching for user data retrieval to improve performance.
- Updated `AppServiceProvider` to use View composer for sharing user data across views.
- Navbar now dynamically adjusts based on user roles (e.g., admin or regular user).
- Used `View::composer` in `AppServiceProvider` to share user data dynamically.
- Caching implemented with `Cache::remember` for efficient user data fetching.
- Handled invalid tokens by clearing sessions to maintain security.
- Improved security by restricting unauthorized access.
- Enhanced performance by reducing repetitive API calls with caching.
- Better UX with dynamic navbar adjustments.
1. Log in as a regular user and verify that the navbar shows options relevant to users.
2. Log in as an …
=> Implement RBAC, View composer, and caching for dynamic navbar and user access control

resources/views/consoles.blade.php, resources/views/games.blade.php, resources/views/home.blade.php
1. Memperbaiki tampilan produk pada halaman home
2. Memperbaiki tampilan produk pada halaman game
3. Memperbaiki tampilan produk pada halaman console
=> Style: Update tampilan produk pada halaman home, game dan console

app/Http/Controllers/Auth/AuthentikasiController.php, resources/views/components/profile-sidebar.blade.php, resources/views/profile-users/change-password.blade.php, resources/views/profile-users/history-order.blade.php, resources/views/profile-users/profile.blade.php, routes/web.php
menambahkan fitur update data user pada controller dan menjalankannya di view
menambahkan route sesuai kebutuhan
=> update : merubah sidebar di /profile-users/ jadi modular

app/Http/Controllers/HomeController.php, resources/views/ewallet.blade.php, resources/views/login/index.blade.php, resources/views/register/index.blade.php, routes/web.php
1. Menampilkan data produk pada halaman e-wallet
2. Memfungsikan ikon mata pada halaman login dan regis
3. Membuat routes untuk menampilkan data produk pada halaman e-wallet
=> Style : update menampilkan data produk pada halaman e-wallet

resources/views/components/navbar-dashboard.blade.php, resources/views/components/navbar.blade.php
Update URL route untuk kategori dan genre di dalam live searching dashboard admin, serta implementasi live search di halaman home
=> FIX: Update URL route dan implementasi live search di halaman home

app/Http/Controllers/InventoryController.php, resources/views/cart.blade.php, resources/views/components/layout.blade.php, resources/views/profile-users/history-order.blade.php, routes/web.php, vite.config.js
=> feat : menambahkan data ke history-order.blade.php setelah dilakukannya proses tambahkan ke keranjang

resources/views/components/navbar-dashboard.blade.php, resources/views/components/navbar.blade.php
live searching mobile di dashboard admin belum berfungsi
=> style : update live searching mobile

app/Http/Controllers/InventoryController.php, app/Models/Cart.php, database/migrations/2024_12_31_235203_create_carts_table.php, database/migrations/2025_01_01_041023_add_status_to_inventory_table.php, resources/views/cart.blade.php, resources/views/components/layout.blade.php, resources/views/profile-users/history-order.blade.php, routes/web.php
creating models, changing and adding some functions in InventoryController
adding new migrations
=> feat : cart, status item in history-order

app/Http/Controllers/PaymentController.php, resources/views/components/navbar-dashboard.blade.php, resources/views/payment/form-payment.blade.php, resources/views/profile-users/history-order.blade.php, routes/web.php
sekarang kalo payment, langsung ngubah status cart dari active jadi completed, status inventory dari progress ke completed.
=> feat : payment

resources/views/cart-back.blade.php, resources/views/cart.blade.php, routes/web.php
1. Menambahkan cart box product
2. Menambahkan routes cart box product
=> Style :  Menambahkan cart box product

app/Http/Controllers/PaymentController.php, config/database.php, resources/views/cart.blade.php, routes/web.php
change password with your actual password in databases.php
=> fix payment dual method (buynow and charts)

app/Http/Controllers/TransactionController.php, app/Models/Transaction.php, composer.lock, resources/views/dashboard/index.blade.php, resources/views/dashboard/transactions/index.blade.php, resources/views/dashboard/transactions/show.blade.php, routes/api.php, routes/web.php
=> Transaction.php
